name: "geodream"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  batch_size: [1, 1]
  # 0-4999: 64x64, >=5000: 512x512
  # this drastically reduces VRAM usage as empty space is pruned in early training
  width: [256, 512]
  height: [256, 512]
  resolution_milestones: [3000]
  camera_distance_range: [1.0, 1.5]
  fovy_range: [40, 60]
  elevation_range: [-35, 35]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_camera_distance: 1.25
  eval_fovy_deg: 50.
  eval_elevation_deg: -15

system_type: "prolificdreamerLR-system"
system:
  stage: coarse
  geometry_type: "geodream-geometry"
  geometry:
    radius: 1.0
    normal_type: null

    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096
    
    init_volume_path: ???
    sdf_network_grad: false
    # one2345_weight: one2345_weight/ckpt_215000.pth
    one2345_weight: mv-diffusion/One-2-3-45/reconstruction/exp/lod0/checkpoints/ckpt_215000.pth

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true

  renderer_type: "geodream-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 512
    eval_chunk_size: 65568

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    # If you are experiencing unstable connections with Hugging Face
    # please set 'pretrained_model_name_or_path' and 'pretrained_model_name_or_path_lora' to your downloaded guidance model local path
    # pretrained_model_name_or_path: "/share/project/denghaoge/threestudio-main/proficdreamer_weight/stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    front_threshold: 20.
    back_threshold: 40.
    overhead_threshold: 50

  guidance_type: "stable-diffusion-vsd-guidance"
  guidance:
    # pretrained_model_name_or_path: "/share/project/denghaoge/threestudio-main/proficdreamer_weight/stabilityai/stable-diffusion-2-1-base"
    # pretrained_model_name_or_path_lora: "/share/project/denghaoge/threestudio-main/proficdreamer_weight/stabilityai/stable-diffusion-2-1"
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path_lora: "stabilityai/stable-diffusion-2-1"
    guidance_scale: 7.5
    min_step_percent: 0.02
    max_step_percent: [15000, 0.98, 0.5, 15001] # annealed to 0.5 after 5000 steps
    view_dependent_prompting: true

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_vsd: 1.
    lambda_lora: 1.
    lambda_orient: 0.
    lambda_sparsity: 10.
    lambda_opaque: [10000, 0.0, 1000.0, 10001]
    lambda_z_variance: 0.
  
  # update texture
  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      # lr of texture hash encoding
      geometry.encoding:
        lr: 0.005
      # lr of texture mlp
      geometry.feature_network:
        lr: 0.0005
    # update geo
    optimizer_geo:
      name: AdamW
      args:
        betas: [0.9, 0.99]
        eps: 1.e-15
      params:
        # lr of cost volume
        geometry.volume:
          lr: 0.001
    # update others
    optimizer_oth:
      name: AdamW
      args:
        betas: [0.9, 0.99]
        eps: 1.e-15
      params:
        geometry.sdf_layers:
          lr: 0.00001
        geometry.deviation_network:
          lr: 0.00001
        background:
          lr: 0.001
        guidance:
          lr: 0.0001
  
  # update texture
  scheduler:
    name: SequentialLR
    interval: step
    warmup_steps: 3500
    milestones:
      - ${system.scheduler.warmup_steps}
    schedulers:
      - name: ConstantLR
        args:
          factor: 1
          total_iters: ${system.scheduler.warmup_steps}
      - name: LinearLR # linear warm-up in the first system.warmup_steps steps
        args:
          start_factor: 1
          end_factor: 0.05
          total_iters: 20000
    # update geo
    scheduler_geo:  
      name: SequentialLR
      interval: step
      milestones:
        - ${system.scheduler.warmup_steps}
      schedulers:
        - name: ConstantLR
          args:
            factor: 1
            total_iters: ${system.scheduler.warmup_steps}
        - name: LinearLR # linear warm-up in the first system.warmup_steps steps
          args:
            start_factor: 0.1
            end_factor: 1
            total_iters: 20000

trainer:
  max_steps: 40000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 500
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: 20000
