name: "geodream-dmtnet-texture"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  batch_size: 1
  width: 1024
  height: 1024
  camera_distance_range: [1.0, 1.25]
  fovy_range: [40, 60]
  elevation_range: [-60, 10]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_camera_distance: 1.125
  eval_fovy_deg: 50.
  eval_elevation_deg: -15
  eval_height: 1024
  eval_width: 1024

system_type: "prolificdreamer-system"
system:
  stage: texture
  geometry_convert_from: ???
  geometry_type: "tetrahedra-sdf-grid"
  geometry:
    radius: 1.0 # consistent with last stage
    isosurface_resolution: 256 # consistent with last stage
    isosurface_deformable_grid: true
    isosurface_remove_outliers: true
    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096
    fix_geometry: true

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid

  renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: gl

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "/share/project/denghaoge/threestudio-main/proficdreamer_weight/stabilityai/stable-diffusion-2-1-base"
    # pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    front_threshold: 20.
    back_threshold: 40.
    overhead_threshold: 50

  guidance_type: "stable-diffusion-vsd-guidance"
  guidance:
    pretrained_model_name_or_path: "/share/project/denghaoge/threestudio-main/proficdreamer_weight/stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path_lora: "/share/project/denghaoge/threestudio-main/proficdreamer_weight/stabilityai/stable-diffusion-2-1"
    # pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    # pretrained_model_name_or_path_lora: "stabilityai/stable-diffusion-2-1"
    guidance_scale: 7.5
    min_step_percent: 0.02
    max_step_percent: [3000, 0.98, 0.4, 3001] # annealed to 0.5 after 5000 steps

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_vsd: 1.
    lambda_lora: 1.
  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.0025
      geometry.feature_network:
        lr: 0.00025
      background:
        lr: 0.00005
      guidance:
        lr: 0.000025

trainer:
  max_steps: 25000
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  val_check_interval: 1500
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: 10000
