name: "geodream-dmtnet-geometry"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  batch_size: 8
  width: 512
  height: 512
  camera_distance_range: [1.0, 1.25]
  fovy_range: [40, 60]
  elevation_range: [-50, 10]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_camera_distance: 1.125
  eval_fovy_deg: 50.
  eval_elevation_deg: -15
  
system_type: "prolificdreamer-system"
system:
  stage: geometry
  geometry_convert_from: ???
  geometry_type: "tetrahedra-sdf-grid"
  geometry:
    radius: 1.0 # consistent with coarse
    isosurface_resolution: 256
    isosurface_deformable_grid: true
    geometry_only: false

  material_type: "no-material" # unused
  material:
    n_output_dims: 0

  background_type: "solid-color-background" # unused

  renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: gl

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    # pretrained_model_name_or_path: "/share/project/denghaoge/threestudio-main/proficdreamer_weight/stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???

  guidance_type: "stable-diffusion-guidance"
  guidance:
    # pretrained_model_name_or_path: "/share/project/denghaoge/threestudio-main/proficdreamer_weight/stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    guidance_scale: 100.
    min_step_percent: 0.02
    max_step_percent: [2000, 0.98, 0.5, 2001] # annealed to 0.5 after 5000 steps
    weighting_strategy: sds

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_sds: 1.
    lambda_normal_consistency: 10000.
    lambda_laplacian_smoothness: 10000.

  optimizer:
    name: Adam
    args:
      lr: 0.001
      betas: [0.9, 0.99]
      eps: 1.e-15

trainer:
  max_steps: 5000
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  val_check_interval: 500
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
