model:
  target: mvdream.ldm.interface.LatentDiffusionInterface
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    timesteps: 1000
    scale_factor: 0.18215
    parameterization: "eps"

    unet_config:
      target: mvdream.ldm.modules.diffusionmodules.openaimodel.MultiViewUNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: False
        legacy: False
        camera_dim: 16

    first_stage_config:
      target: mvdream.ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: mvdream.ldm.modules.encoders.modules.FrozenCLIPEmbedder
